DOCS = Extended_Data_Figures
DEPENDS = $(wildcard challenge1_src/*.pdf) \
	 $(wildcard challenge2_src/*.pdf) \
	 $(wildcard challenge3_src/*.pdf) \
	 $(wildcard validation_src/*.pdf)

include ../figure-rules.mk

