DOCS = Supplementary_Figures
DEPENDS = $(wildcard overview_src/*.pdf) \
	 $(wildcard challenge1_src/*.pdf) \
	 $(wildcard challenge1_src/*/*.pdf) \
	 $(wildcard challenge1_src/*/*/*.pdf) \
	 $(wildcard challenge2_src/*.pdf) \
	 $(wildcard challenge3_src/*.pdf) \
	 $(wildcard validation_src/*.pdf)

include ../figure-rules.mk

